test: drop unused include from test-parse-util.c
Fix clang-tidy regression:

../src/test/test-parse-util.c:11:1: error: included header string-util.h is not used directly [misc-include-cleaner,-warnings-as-errors]
   11 | #include "string-util.h"
      | ^~~~~~~~~~~~~~~~~~~~~~~~
   12 | #include "tests.h"

Follow-up for efdc4b0cc7dbf47f6ab08dd997b7dba1699be3e4