bpf: fix is_allow_list section
The llvm bpf compiler appears to place const volatile variables in
the wrong section which creates an incompatibility with the gcc bpf
compiler.

To fix this force the variable to be placed in the correct .data
section instead of the incorrect .rodata section.

See:
https://github.com/llvm/llvm-project/issues/56468

Fixes:
../src/core/restrict-ifaces.c:45:14: error: ‘struct
restrict_ifaces_bpf’ has no member named ‘rodata’; did you mean
‘data’?
   45 |         obj->rodata->is_allow_list = is_allow_list;
      |              ^~~~~~
      |              data