tests: bump up QEMU_MEM so that ASan can allocate enough memory
==198==ERROR: AddressSanitizer failed to allocate 0x202000 (2105344) bytes of LargeMmapAllocator (errno: 12)
==198==Process memory map follows:
...
==198==End of process memory map.
==198==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/sanitizer_common/sanitizer_posix.cc:121 "(("unable to mmap" && 0)) != (0)" (0x0, 0x0)
ERROR: Failed to mmap