string-util: introduce strrepa
Also the test case when n == 0 is removed,
because for the stack allocation variant
it fails with

../src/basic/string-util.h:204:44: error: comparison of unsigned expression is always false [-Werror=type-limits]
  204 |                 for (unsigned _i_ = 0; _i_ < n; _i_++)          \
      |                                            ^
../src/test/test-string-util.c:274:17: note: in expansion of macro strrepa
  274 |         zeroa = strrepa("waldo", 0);

and it's not really useful after all.