utmp-wtmp: add several missing definitions for musl
This is to avoid build failures like the following:
  test-utmp.c:30:39: error: ‘ACCOUNTING’ undeclared (first use in this function)

Upstream-Status: Inappropriate [musl specific]
Signed-off-by: Yu Watanabe <watanabe.yu+github@gmail.com>