mkosi: define ext_man macro in suse rpm build
The suse spec now uses:

 %{_mandir}/man3/*.3%{?ext_man}

which defaults to .gz and fails, as we disable compression.
Redefine it to avoid a build failure:

 Processing files: systemd-doc-260.2-00.noarch
 error: File not found: /var/tmp/BUILD/systemd-260.2-build/BUILDROOT/usr/share/man/man3/*.3.gz

(cherry picked from commit 785e4c00a769b97a73719ff65dbb7807b55fde8a)
(cherry picked from commit 7ac23f8fd49551bf39c83e539d1d4892ad2cf54d)
(cherry picked from commit 387fab4bbeb3f8feb6dc80f1b86bbaa5ad40bd27)