really really fix both in-tree and out-of-tree builds
The include is still missing:
  GEN    extras/gudev/GUdev-1.0.gir
  In file included from <stdin>:4:
  /home/kay/work/src/udev/extras/gudev/gudev.h:26:34: error: gudev/gudevenumtypes.h: No such file or directory

Also prepend $(builddir).