fix(copy): declaration of unsigned variable
`z` should be `size_t` instead of `ssize_t` because of the following
line:

```c
z = (size_t) n;
```

This also makes coverity a bit happier:

```c
Error: INTEGER_OVERFLOW (CWE-190):
systemd-256/src/shared/copy.c:459:33: tainted_data_return: Called function "write(fdt, p, z)", and a possible return value may be less than zero.
systemd-256/src/shared/copy.c:459:33: assign: Assigning: "k" = "write(fdt, p, z)".
systemd-256/src/shared/copy.c:480:33: overflow: The expression "z" is considered to have possibly overflowed.
systemd-256/src/shared/copy.c:459:33: overflow_sink: "z", which might have overflowed, is passed to "write(fdt, p, z)".
  457|                                   ssize_t k;
  458|
  459|->                                 k = write(fdt, p, z);
  460|                                   if (k < 0) {
  461|                                           r = -errno;
```