semaphore: disable LTO
Breaks EFI build with gcc 12.2.0

../src/boot/efi/stub.c: In function ‘load_addons.constprop.0’:04:04
../src/boot/efi/stub.c:475:40: error: using a dangling pointer to ‘p’ [-Werror=dangling-pointer=]04:04
  475 |                         dt_bases[n_dt] = xmemdup((uint8_t*)loaded_addon->ImageBase + addrs[UNIFIED_SECTION_DTB],04:04
      |                         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~04:04
  476 |                                                  dt_sizes[n_dt]);04:04
      |                                                  ~~~~~~~~~~~~~~~04:04
In file included from ../src/boot/efi/stub.c:20:04:04
../src/boot/efi/util.h:33:15: note: ‘p’ declared here04:04
   33 |         void *p = NULL;