include: add several missing utmpx related macros for musl
This is to avoid build failures like the following:
  test-utmp.c:30:39: error: ‘ACCOUNTING’ undeclared (first use in this function)