locale: add libxkbcommon_deps to test-localed-util build
Fixes build on SUSE Tumbleweed:

[1459/2241] Compiling C object test-localed-util.p/src_locale_xkbcommon-util.c.o
FAILED: test-localed-util.p/src_locale_xkbcommon-util.c.o
cc -Itest-localed-util.p -I. -I../src -Isrc/basic -I../src/src/basic -Isrc/fundamental -I../src/src/fundamental -Isrc/systemd -I../src/src/systemd -I../src/src/libsystemd/sd-bus -I../src/src/libsystemd/sd-device -I../src/src/libsystemd/sd-event -I../src/src/libsystemd/sd-hwdb -I../src/src/libsystemd/sd-id128 -I../src/src/libsystemd/sd-journal -I../src/src/libsystemd/sd-netlink -I../src/src/libsystemd/sd-network -I../src/src/libsystemd/sd-resolve -Isrc/shared -I../src/src/shared -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -O0 -g -Wno-missing-field-initializers -Wno-unused-parameter -Warray-bounds -Warray-bounds=2 -Wdate-time -Wendif-labels -Werror=format=2 -Werror=format-signedness -Werror=implicit-function-declaration -Werror=implicit-int -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=missing-declarations -Werror=missing-prototypes -Werror=overflow -Werror=override-init -Werror=return-type -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunused-function -Wwrite-strings -Wzero-length-bounds -fdiagnostics-show-option -fno-common -fstack-protector -fstack-protector-strong -fstrict-flex-arrays --param=ssp-buffer-size=4 -Wno-unused-result -Werror=shadow -fno-strict-aliasing -fstrict-flex-arrays=1 -fvisibility=hidden -fno-omit-frame-pointer -include config.h -DTEST_CODE=1 -MD -MQ test-localed-util.p/src_locale_xkbcommon-util.c.o -MF test-localed-util.p/src_locale_xkbcommon-util.c.o.d -o test-localed-util.p/src_locale_xkbcommon-util.c.o -c ../src/src/locale/xkbcommon-util.c
In file included from ../src/src/locale/xkbcommon-util.c:7:
../src/src/locale/xkbcommon-util.h:5:10: fatal error: xkbcommon/xkbcommon.h: No such file or directory
    5 | #include <xkbcommon/xkbcommon.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~

Follow-up for 0327d5b20f9e845dc310cb9e87207ac982c8bbd0