mkosi: temporary disable installing wireguard-tools
Currently wireguard-tools-wg-quick-systemd from postmarketOS and
wireguard-tools-systemd conflict with each other.
```
(476/499) Installing wireguard-tools-wg (1.0.20250521-r1)
(477/499) Installing systemd-resolved (259_rc1-r1763636956)
(478/499) Installing wireguard-tools-wg-quick (1.0.20250521-r1)
(479/499) Installing wireguard-tools-wg-quick-systemd (101-r0)
(480/499) Installing wireguard-tools (1.0.20250521-r1)
(481/499) Installing wireguard-tools-bash-completion (1.0.20250521-r1)
(482/499) Installing wireguard-tools-systemd (1.0.20250521-r1)
ERROR: wireguard-tools-systemd-1.0.20250521-r1: trying to overwrite usr/lib/systemd/system/wg-quick@.service owned by wireguard-tools-wg-quick-systemd-101-r0.
```