semaphore: switch to another keyserver
lxc-create has been failing to download the image today with
```
+ sudo lxc-create -n buster-amd64 -t download -- -d debian -r buster -a amd64
Setting up the GPG keyring
ERROR: Unable to fetch GPG key from keyserver
lxc-create: buster-amd64: lxccontainer.c: create_run_template: 1617 Failed to create container from template
lxc-create: buster-amd64: tools/lxc_create.c: main: 327 Failed to create container buster-amd64
```
Let's try another keyserver.