udev: Use struct key instead of struct key_name
Gperf creates functions returning a struct key, fix udev builtin
keyboard to return the same. The compilation error leading up to
this is:

  CC       src/udev/libudev_core_la-udev-builtin-keyboard.lo
In file included from src/udev/udev-builtin-keyboard.c:33:0:
src/udev/keyboard-keys-from-name.h:123:1: error: conflicting types for ‘keyboard_lookup_key’
 keyboard_lookup_key (register const char *str, register unsigned int len)
 ^~~~~~~~~~~~~~~~~~~
src/udev/udev-builtin-keyboard.c:32:31: note: previous declaration of ‘keyboard_lookup_key’ was here
 static const struct key_name *keyboard_lookup_key(const char *str, GPERF_LEN_TYPE len);
                               ^~~~~~~~~~~~~~~~~~~
src/udev/udev-builtin-keyboard.c: In function ‘map_keycode’:
src/udev/udev-builtin-keyboard.c:83:11: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
         k = keyboard_lookup_key(keycode, strlen(keycode));
           ^
src/udev/udev-builtin-keyboard.c:85:32: error: dereferencing pointer to incomplete type ‘const struct key_name’
                 keycode_num = k->id;
                                ^~
cc1: some warnings being treated as errors
Makefile:19349: recipe for target 'src/udev/libudev_core_la-udev-builtin-keyboard.lo' failed