ukify: drop uapi-group URL from stub SBAT entry
Fedora's kernels now ship with a .sbat section:

kernel,1,Red Hat,kernel-core,6.17.0-0.rc1.250814g0cc53520e68b.20.fc44.x86_64,mailto:secalert@redhat.com
kernel.fedora,1,Red Hat,kernel-core,6.17.0-0.rc1.250814g0cc53520e68b.20.fc44.x86_64,mailto:secalert@redhat.com

This pushes the combined .sbat section just over its pre-allocated
size of 512 bytes:

File "/usr/bin/ukify", line 1048, in pe_add_sections    raise PEError(f'Not enough space in existing section {section.name} to append new data')
PEError: Not enough space in existing section .sbat to append new data

PE sections need to align to 512 bytes, so to make it all fit we'd need to pad
every UKI .sbat section to 1KB, even if not needed.

Drop the URL to the uapi-group UKI spec, as it doesn't seem very useful
to have and was basically a placeholder.

A more durable solution would be to delete and recreate the .sbat
section instead of appending data to it, but given it's in the pre-built
stub binary that is not a trivial change.