fix build with recent glibc
http://38.145.33.116/systemd-pr/ff/84/ff84e0e7d0c9ff2b4b998f856da02bbae7ca1806_dev/build.log.gz
Fedora 28 rawhide

Checking for function "copy_file_range": NO

../src/basic/missing_syscall.h:310:23: error: static declaration of 'copy_file_range' follows non-static declaration
 static inline ssize_t copy_file_range(int fd_in, loff_t *off_in,
                       ^~~~~~~~~~~~~~~
In file included from ../src/basic/bpf-program.c:24:0:
/usr/include/unistd.h:1110:9: note: previous declaration of 'copy_file_range' was here
 ssize_t copy_file_range (int __infd, __off64_t *__pinoff,
         ^~~~~~~~~~~~~~~
The this requires _GNU_SOURCE is not documented in the man page

https://sourceware.org/git/?p=glibc.git;a=commit;f=posix/unistd.h;h=bad7a0c81f501fbbcc79af9eaa4b8254441c4a1f