meson: newer qemu requires '-machine' for '-device help'
Fixes the following error in Fedora rawhide:
```
test/integration-tests/TEST-64-UDEV-STORAGE/meson.build:14:18:
ERROR: Command `/usr/sbin/qemu-system-x86_64 -device help` failed with status 127.
```
Old qemu provides list of devices even with '-machine virt'.
Let's unconditionally append '-machine virt'.