test: add missing FTW_CONTINUE macro for musl
This is to avoid build failures like below for musl.

  test-recurse-dir.c:23:24: error: ‘FTW_CONTINUE’ undeclared

Upstream-Status: Inappropriate [musl specific]
Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
[Rebased for v258]
Signed-off-by: Yu Watanabe <watanabe.yu+github@gmail.com>