missing_sched: add CLONE_PIDFD
CLONE_PIDFD was introduced in v5.2 so without this, building with older
Linux kernel headers fails with:

src/basic/raw-clone.h:41:108: error: 'CLONE_PIDFD' undeclared (first use in this function); did you mean 'CLONE_FILES'?